### ISSUE TITLE
task not sorting, what I'm doing wrong?

### ISSUE THREAD

**Issue by iamstarkov** [csscomb/grunt-csscomb#23]
I have such [CSScomb.json](https://gist.github.com/matmuchrapna/8929541) in the root of the project. Also I have css-file with path like this `static/desktop.bundles/wizard/blocks/wizard-steps/wizard-steps.css`. Also task is configured this way:

``` js
csscomb: {
    options: {
        config: 'CSScomb.json'
    },
    all: {
        expand: true,
        cwd: 'static/',
        src: [ '**/*.css' ],
        dest: 'static/'
    }
}
```

When I run CSScomb with `$ grunt csscomb:all` task logs sorting `wizard-steps.css`:

```
>> Sorting file "static/desktop.bundles/wizard/blocks/wizard-steps/wizard-steps.css"...
```

But original state of this file is: 

``` css
 .wizard-steps
{
    margin: 50px 0 0;
    display: block;
}
```

and it's not changed via grunt-csscomb, but when I sort this file with Sublime CSScomb it changed to normal and expected state:

``` css
.wizard-steps
{
    display: block;

    margin: 50px 0 0;
}
```

What I'm doing wrong?
